### PR TITLE
WIP: Add UART peripheral mapping.

### PR DESCRIPTION
**Pull request by thvdveld**
This adds the UART peripheral mapping for the CC2538.

~~Currently, all registers are read-write, because the registers in the provided SVD file don't contain the access field. Still need to patch this.~~

I'm also not sure if my method of patching the reserved fields in the registers is the correct way of doing it.

### CODE REVIEW

**Comment by alfredch** [comment]
Thank you for your PR! 
I am in the process of making proper CMSIS/SVD files for all the TI-SimpleLink devices. The aim is that they become CMSIS-SVD_Schema-conform and can be processed in drone-tisl.

**Comment by thvdveld** [comment]
> I am in the process of making proper CMSIS/SVD files for all the TI-SimpleLink devices. The aim is that they become CMSIS-SVD_Schema-conform and can be processed in drone-tisl.

Nice! This will reduce the amount of patches!
Any idea on how to tackle the reserved fields? Will they be omitted in the new SVD files? Because, currently, a lot of registers have those reserved fields and I removed them in `fn remove_reserved(...)`.

**Comment by alfredch** [comment]
At first glance I would say our SVDs should not include registers who's ID (in the modules files of TI's "targetdb") begins with 'RESERVED'.
We first carry out a one-time programmatic transformation process from targetdb->SVD. In a second round, we will have to consult the reference manuals and maybe patch our SVDs,

**Comment by thvdveld** [comment]
I'm going to close this PR (and reopen a new one), because I used my master branch (beginner's mistake).

**Pull request closed without merging**
